name: "Podcast Generator"
author: "Kristen Hyslope"
description: "Generates a feeed for a podcast from a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "purple"
  inputs:
    email:
      description: The commiter's email address
      required: true
      default: ${{ github.actor }}@localhost
    name:
      description: the commiter's name
      required: true
      default: ${{ github.actor }}
