name: "Podcast Generator"
author: "Kristen Hyslope"
description: "Generates a feeed for a podcast from a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "purple"
inputs:
  committer_email:
    description: The committer's email address
    required: true
    default: {{github.actor}@localhost
  committer_name:
    description: The committer's name
    required: true
    default: {{github.actor}}